---

- hosts: db-servers
  roles:
      - mariadb
  vars:
      db_user: "amp"
      db_password: "password"
      production: true

- hosts: app-servers
  roles:
      - django
      - nginx
  vars:
      djangoport: "8080"
      nginxport: "80"
      debug: no
      company: "Test Company"
      url: "http://amp.jteppinette.com"
      dir: /var/www
      secret: "cmttfpnk9+6^vs0ow=umgt3$bue+pm=a&-n&$&6@%ww9gpl2x@"
      db_user: "amp"
      db_password: "password"
      production: yes
