---

- hosts: all
  roles:
      - mariadb
      - nginx
      - django
  vars:
      djangoport: "8080"
      nginxport: "80"
      debug: "False"
      company: "Test Company"
      url: "http://amp.jteppinette.com"
      dir: /var/www
      production: true
      db_user: "amp"
      db_password: "password"
      secret: "cmttfpnk9+6^vs0ow=umgt3$bue+pm=a&-n&$&6@%ww9gpl2x@"
