# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('log_reccurence', models.IntegerField(default=1, help_text=b'Represent the time between automatic log emails. This field is measured in days.')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('employer', models.CharField(max_length=80)),
                ('background_check', models.FileField(blank=True, help_text=b'This field is not required.', null=True, upload_to=b'background')),
                ('last_background_check_date', models.DateField(blank=True, help_text=b'This field is not required. Ex. 2012-05-13', null=True)),
                ('last_training_date', models.DateField(blank=True, help_text=b'This field is not required. Ex. 2012-05-13', null=True)),
                ('company', models.ForeignKey(help_text=b'This field represents the company that the contractor is requesting access to.', on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'contractor-documents')),
                ('contractor', models.ForeignKey(help_text=b'This field represent the contractor that this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('employer', models.CharField(max_length=80)),
                ('remote', models.BooleanField(help_text=b'Will you be accessing remotely?')),
                ('background_check', models.FileField(blank=True, null=True, upload_to=b'background')),
                ('hr_status', models.NullBooleanField()),
                ('tc_status', models.NullBooleanField()),
                ('ace_status', models.NullBooleanField()),
                ('cip_status', models.NullBooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('eid', models.IntegerField(unique=True)),
                ('background_check', models.FileField(blank=True, help_text=b'This field is not required.', null=True, upload_to=b'background')),
                ('last_background_check_date', models.DateField(blank=True, help_text=b'This field is not required. Ex. 2012-05-13', null=True)),
                ('last_training_date', models.DateField(blank=True, help_text=b'This is field is not required. Ex. 2012-05-13', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'employee-documents')),
                ('employee', models.ForeignKey(help_text=b'This field represent the employee that this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_status', models.NullBooleanField()),
                ('tc_status', models.NullBooleanField()),
                ('ace_status', models.NullBooleanField()),
                ('cip_status', models.NullBooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(b'Approval', b'Approval'), (b'Rejection', b'Rejection'), (b'New Employee', b'New Employee'), (b'New Contractor', b'New Contractor'), (b'Permission Change', b'Permission Change'), (b'New Employee Permission Request', b'New Employee Permission Request'), (b'New Contractor Permission Request', b'New Contractor Permission Request')], max_length=160)),
                ('author', models.CharField(max_length=160)),
                ('accessor', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='permissions',
            field=models.ManyToManyField(to='app.Permission'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='app.Permission'),
        ),
        migrations.AddField(
            model_name='contractorrequest',
            name='permissions',
            field=models.ManyToManyField(to='app.Permission'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='app.Permission'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('company', 'eid'), ('first_name', 'last_name', 'company')]),
        ),
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together=set([('first_name', 'last_name', 'company')]),
        ),
    ]
