# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('title', models.CharField(blank=True, choices=[(b'CIP Manager', b'CIP Manager'), (b'Alternate CIP Manager', b'Alternate CIP Manager'), (b'Access Control Engineer', b'Access Control Engineer'), (b'Training Coordinator', b'Training Coordinator'), (b'Human Resources', b'Human Resources')], max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
