"""
Define the views used to render the AMP Logs pages.
"""

from django.views.generic import ListView

from api.models import Log

class ListLogs(ListView):
    """
    List the logs that are generated by AMP.
    """
    queryset = Log.objects.all().order_by('-creation_time')
    template_name = 'logs.html'
